export const RETRIEVE_PRODUCTS= "RETRIEVE_PRODUCTS";
export const RETRIEVE_CATEGORIES= "RETRIEVE_CATEGORIES";
export const RETRIEVE_CART_DETAILS= "RETRIEVE_CART_DETAILS";
export const ADD_TO_CART= "ADD_TO_CART";
export const REMOVE_FROM_CART= "REMOVE_FROM_CART";
export const GET_CART_ITEMS= "GET_CART_ITEMS";


